version: "3.3"

services:
  db:
    restart: always
    image: postgres
    restart: always
    build:
      context: docker-postgres
      args:
        - DB_POSTGRES_FROM_IMAGE=${DB_POSTGRES_FROM_IMAGE}
        - DB_POSTGIS_VERSION=${DB_POSTGIS_VERSION}
    hostname: ${DB_POSTGRES_HOST_NAME}
    container_name: ${DB_POSTGRES_HOST_NAME}
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRES_DB}
      - PGDATA=/storage/db/data
    networks:
      - project_net_kupistar
    volumes:
      - ./storage/data/postgres:/storage/db/data
      - ./storage/log:/storage/db/log
    ports:
      - "${DB_POSTGRES_EXT_HOST_IP}:${DB_POSTGRES_EXT_PORT}:${DB_POSTGRES_INT_PORT}"
  user-balance:
    build: .
    ports:
      - "8080:8080"